path = 'C:/Users/Thrus/Desktop/';
Array = csvread(fullfile(path, 'fy_outlast.csv'), 3, 1);
cla;
hold on;
plotX = 1 : size(Array, 1);
plot(plotX, Array(:, 2));
xlabel('Time [s]');
ylabel('Heartbeat [bpm]');
title('ECG');
% plot(plotX, Array(:, 4));
%k = butterFilter_realtime(Array(:, 2 : 4).', 100, 1);
% disp(getVitalRate(k, 100, 1));
%plot(plotX, k(2, :));